"""Auto-generate LaTeX critical editions from structured JSON data.

Reads the variant table and individual witness JSON files to produce
five camera-ready LaTeX critical editions:
  - Chinese critical edition (T251 base)
  - Sanskrit critical edition (GRETIL base)
  - Tibetan critical edition (Toh21 base)
  - Parallel synoptic edition (three-column landscape)
  - Combined critical edition (three-column landscape with full apparatus)

Usage:
    PYTHONPATH=src python -m hrdaya.latex_gen
    PYTHONPATH=src python -m hrdaya.latex_gen --edition chinese
"""

from __future__ import annotations

import json
import logging
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from .data import DATA_VERSION, compute_data_hash, resolve_data_dir

logger = logging.getLogger(__name__)

# ============================================================================
# Constants
# ============================================================================

SECTIONS = [
    ("opening", "Opening"),
    ("form_emptiness", "Form and Emptiness"),
    ("characteristics", "Characteristics"),
    ("negations_skandhas", "Negations: Skandhas"),
    ("negations_ayatanas", "Negations: Āyatanas"),
    ("negations_dhatus", "Negations: Dhātus"),
    ("negations_pratityasamutpada", "Negations: Pratītyasamutpāda"),
    ("negations_truths", "Negations: Noble Truths"),
    ("bodhisattva_result", "Bodhisattva Result"),
    ("buddha_result", "Buddha Result"),
    ("mantra_praise", "Mantra Praise"),
    ("mantra", "Mantra"),
]

SECTION_KEYS = [k for k, _ in SECTIONS]
SECTION_TITLES = dict(SECTIONS)


def _escape_latex(text: str) -> str:
    """Escape LaTeX special characters in plain text.

    CJK, Devanagari, and Tibetan characters pass through unchanged
    since XeLaTeX handles them via fontspec.
    """
    # Use placeholder for backslash to avoid double-escaping the {}
    _bs = "\x00BS\x00"
    text = text.replace("\\", _bs)
    for ch, repl in [
        ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
        ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
        ("}", r"\}"), ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]:
        text = text.replace(ch, repl)
    text = text.replace(_bs, r"\textbackslash{}")
    return text


def _split_chinese_clauses(text: str) -> list[str]:
    """Split Chinese text into clauses at sentence/clause boundaries.

    Splits at 。，；：（but keeps the punctuation attached to the
    preceding text. Returns a list of clauses.
    """
    clauses = []
    current = []
    for ch in text:
        current.append(ch)
        if ch in "。，；：":
            clauses.append("".join(current))
            current = []
    if current:
        clauses.append("".join(current))
    return [c for c in clauses if c.strip()]


def _provenance_header(data_hash: str) -> str:
    """Generate a provenance comment for the top of a .tex file."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"%% AUTO-GENERATED by hrdaya.latex_gen\n"
        f"%% Data version: {DATA_VERSION}  Hash: {data_hash}\n"
        f"%% Generated: {now}\n"
        f"%% Regenerate with: make latex-gen\n"
    )


# ============================================================================
# Data classes
# ============================================================================

@dataclass
class ApparatusEntry:
    """A single apparatus footnote entry."""
    lemma: str
    readings: list[tuple[str, list[str]]]  # [(variant_text, [witness_ids])]
    note: str = ""


# ============================================================================
# DataLoader
# ============================================================================

class DataLoader:
    """Load variant table and witness JSON files."""

    def __init__(self, data_dir: Path):
        self.data_dir = data_dir
        self._variant_table: dict | None = None
        self._witnesses: dict[str, dict] = {}

    def load_variant_table(self) -> dict:
        """Load and cache the variant table."""
        if self._variant_table is None:
            vt_path = self.data_dir / "collation" / "variant_table.json"
            if not vt_path.exists():
                raise FileNotFoundError(
                    f"Variant table not found: {vt_path}\n"
                    "Run 'make collation' first."
                )
            self._variant_table = json.loads(vt_path.read_text(encoding="utf-8"))
        return self._variant_table

    def load_witness(self, witness_id: str) -> dict:
        """Load a witness JSON file by ID, searching subdirectories."""
        if witness_id in self._witnesses:
            return self._witnesses[witness_id]

        # Try multiple filename variants (case sensitivity)
        candidates = [f"{witness_id.lower()}.json", f"{witness_id}.json"]
        # Special case: GRETIL uses a different filename
        if witness_id == "GRETIL":
            candidates = ["prajnaparamitahrdaya.json"]

        # Search all subdirectories
        for filename in candidates:
            for json_path in self.data_dir.rglob(filename):
                # Skip collation directory
                if "collation" in json_path.parts:
                    continue
                try:
                    data = json.loads(json_path.read_text(encoding="utf-8"))
                    self._witnesses[witness_id] = data
                    return data
                except (json.JSONDecodeError, OSError) as e:
                    logger.warning("Failed to load %s: %s", json_path, e)

        logger.warning("Witness not found: %s", witness_id)
        self._witnesses[witness_id] = {}
        return {}

    def get_segment(self, witness_id: str, segment_id: str) -> dict:
        """Get a specific segment from a witness by segment ID."""
        data = self.load_witness(witness_id)
        for seg in data.get("segments", []):
            if seg.get("id") == segment_id:
                return seg
        return {}

    def get_segment_by_parallel(self, witness_id: str, base_id: str) -> dict:
        """Get a segment from a witness by its base_parallel reference."""
        data = self.load_witness(witness_id)
        for seg in data.get("segments", []):
            if seg.get("base_parallel") == base_id:
                return seg
        return {}


# ============================================================================
# ApparatusAssembler
# ============================================================================

class ApparatusAssembler:
    """Build apparatus entries from variant table + witness data."""

    def __init__(self, loader: DataLoader):
        self.loader = loader

    def assemble_chinese(self, section: str) -> list[ApparatusEntry]:
        """Build Chinese-tradition apparatus entries for a section."""
        vt = self.loader.load_variant_table()
        entries_data = vt.get("sections", {}).get(section, [])
        result = []
        for entry in entries_data:
            for variant in entry.get("variants", []):
                # Only Chinese intra-linguistic variants (position >= 0)
                witnesses = variant.get("witnesses", [])
                if variant.get("position", -1) < 0:
                    continue
                note = variant.get("note", "")
                # Supplement empty notes from witness data
                if not note:
                    note = self._supplement_chinese_note(
                        entry["segment_id"], variant, witnesses
                    )
                # Extract lemma from position
                lemma = self._extract_lemma(
                    entry["base_text"], variant
                )
                result.append(ApparatusEntry(
                    lemma=lemma,
                    readings=[(variant["variant_reading"], witnesses)],
                    note=note,
                ))
        return result

    def assemble_cross_linguistic(
        self, section: str, tradition: str
    ) -> list[ApparatusEntry]:
        """Build cross-linguistic apparatus entries for a section."""
        vt = self.loader.load_variant_table()
        entries_data = vt.get("sections", {}).get(section, [])
        result = []
        for entry in entries_data:
            for variant in entry.get("variants", []):
                if variant.get("position", 0) != -1:
                    continue
                witnesses = variant.get("witnesses", [])
                # Filter by tradition
                if tradition == "sanskrit" and "GRETIL" not in witnesses:
                    continue
                if tradition == "tibetan" and "Toh21" not in witnesses:
                    continue
                note = variant.get("note", "")
                result.append(ApparatusEntry(
                    lemma=entry["base_text"][:20] + "…",
                    readings=[(variant["variant_reading"], witnesses)],
                    note=note,
                ))
        return result

    def _supplement_chinese_note(
        self, segment_id: str, variant: dict, witnesses: list[str]
    ) -> str:
        """Try to fill an empty note from witness-level data."""
        # Check T250's variants_from_T251
        if "T250" in witnesses:
            t250_seg = self.loader.get_segment_by_parallel("T250", segment_id)
            variants_list = t250_seg.get("variants_from_T251", [])
            if variants_list:
                return variants_list[0]
        # Check Fangshan's comparison_T251
        if "Fangshan" in witnesses:
            fs_seg = self.loader.get_segment_by_parallel("Fangshan", segment_id)
            comp = fs_seg.get("comparison_T251", "")
            if comp and comp != "identical":
                return comp
        return ""

    def _extract_lemma(self, base_text: str, variant: dict) -> str:
        """Extract the lemma (annotated portion) from the base text."""
        pos = variant.get("position", 0)
        var_reading = variant.get("variant_reading", "")
        if pos < 0 or pos >= len(base_text):
            # Whole-segment or out of range — use first few chars
            return base_text[:10] + ("…" if len(base_text) > 10 else "")
        # Use variant reading length as guide for lemma span, capped at 6
        span = min(max(len(var_reading), 2), 6)
        lemma_end = min(pos + span, len(base_text))
        lemma = base_text[pos:lemma_end]
        # Trim at a natural boundary if possible
        for punct in "，。；：":
            idx = lemma.find(punct)
            if idx > 0:
                lemma = lemma[:idx]
                break
        return lemma


# ============================================================================
# Preamble templates
# ============================================================================

_FONTS_MAIN = r"""\setmainfont{Noto Serif}[
  BoldFont = {Noto Serif},
  BoldFeatures = {RawFeature=+axis{wght=700}},
]
\setsansfont{Noto Sans}
\setCJKmainfont{Noto Serif CJK SC}
\setCJKsansfont{Noto Sans CJK SC}"""

_FONT_DEVANAGARI = r"""\newfontfamily\devanagarifont{Noto Serif Devanagari}[
  BoldFont = {Noto Serif Devanagari},
  BoldFeatures = {RawFeature=+axis{wght=700}},
]
\newcommand{\deva}[1]{{\devanagarifont #1}}"""

_FONT_TIBETAN = r"""\newfontfamily\tibetanfont{Noto Serif Tibetan}[
  BoldFont = {Noto Serif Tibetan},
  BoldFeatures = {RawFeature=+axis{wght=700}},
]
\newcommand{\tib}[1]{{\tibetanfont\XeTeXlinebreaklocale "bo" #1}}"""

_COMMANDS_COMMON = r"""\newcommand{\linenum}[1]{\textbf{\small #1.}}
\newcommand{\lemma}[1]{\textbf{#1}}
\newcommand{\reading}[1]{#1}
\newcommand{\wit}[1]{\textsc{#1}}
\newcommand{\gloss}[1]{{\small\color{teal}\textit{#1}}}
\newcommand{\fluent}[1]{{\small #1}}"""


def _preamble_chinese(provenance: str) -> str:
    return f"""{provenance}
\\documentclass[11pt,a4paper]{{article}}

\\usepackage[margin=2.5cm,bottom=3cm]{{geometry}}
\\usepackage{{fontspec}}
\\usepackage{{xeCJK}}
\\usepackage{{xcolor}}
\\usepackage{{longtable}}
\\usepackage{{array}}
\\usepackage{{enumitem}}
\\usepackage[perpage]{{footmisc}}
\\usepackage{{fancyhdr}}
\\pagestyle{{fancy}}
\\fancyhf{{}}
\\renewcommand{{\\headrulewidth}}{{0.4pt}}
\\fancyhead[L]{{\\small Prajñāpāramitāhṛdaya -- Chinese Critical Edition}}
\\fancyhead[R]{{\\small 般若波羅蜜多心經}}
\\fancyfoot[C]{{\\thepage}}

{_FONTS_MAIN}

{_COMMANDS_COMMON}
\\newcommand{{\\pinyin}}[1]{{{{\\small\\color{{gray}} #1}}}}

\\begin{{document}}
"""


def _preamble_sanskrit(provenance: str) -> str:
    return f"""{provenance}
\\documentclass[11pt,a4paper]{{article}}

\\usepackage[margin=2.5cm,bottom=3cm]{{geometry}}
\\usepackage{{fontspec}}
\\usepackage{{xeCJK}}
\\usepackage{{xcolor}}
\\usepackage{{longtable}}
\\usepackage{{array}}
\\usepackage{{enumitem}}
\\usepackage[perpage]{{footmisc}}
\\usepackage{{fancyhdr}}
\\pagestyle{{fancy}}
\\fancyhf{{}}
\\renewcommand{{\\headrulewidth}}{{0.4pt}}
\\fancyhead[L]{{\\small Prajñāpāramitāhṛdaya -- Sanskrit Critical Edition}}
\\fancyhead[R]{{\\small\\devanagarifont प्रज्ञापारमिताहृदय}}
\\fancyfoot[C]{{\\thepage}}

{_FONTS_MAIN}

{_FONT_DEVANAGARI}

{_COMMANDS_COMMON}
\\newcommand{{\\depmark}}[2]{{{{\\small\\color{{blue}}[#1\\,$\\rightarrow$\\,#2]}}}}

\\begin{{document}}
"""


def _preamble_tibetan(provenance: str) -> str:
    return f"""{provenance}
\\documentclass[11pt,a4paper]{{article}}

\\usepackage[margin=2.5cm,bottom=3cm]{{geometry}}
\\usepackage{{fontspec}}
\\usepackage{{xeCJK}}
\\usepackage{{xcolor}}
\\usepackage{{longtable}}
\\usepackage{{array}}
\\usepackage{{enumitem}}
\\usepackage[perpage]{{footmisc}}
\\usepackage{{fancyhdr}}
\\pagestyle{{fancy}}
\\fancyhf{{}}
\\renewcommand{{\\headrulewidth}}{{0.4pt}}
\\fancyhead[L]{{\\small Prajñāpāramitāhṛdaya -- Tibetan Critical Edition}}
\\fancyhead[R]{{\\small\\tibetanfont བཅོམ་ལྡན་འདས་མ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོ}}
\\fancyfoot[C]{{\\thepage}}

{_FONTS_MAIN}

{_FONT_TIBETAN}

{_COMMANDS_COMMON}
\\newcommand{{\\wylie}}[1]{{{{\\small\\color{{gray}} #1}}}}

\\begin{{document}}
"""


def _preamble_parallel(provenance: str) -> str:
    return f"""{provenance}
\\documentclass[10pt,a4paper,landscape]{{article}}

\\usepackage[landscape,margin=1.2cm,bottom=2cm]{{geometry}}
\\usepackage{{fontspec}}
\\usepackage{{xeCJK}}
\\usepackage{{tabularx}}
\\usepackage{{array}}
\\usepackage{{booktabs}}
\\usepackage{{xcolor}}
\\usepackage{{longtable}}
\\usepackage{{multicol}}
\\usepackage[perpage,symbol*]{{footmisc}}
\\renewcommand{{\\thefootnote}}{{\\arabic{{footnote}}}}
\\usepackage{{fancyhdr}}
\\pagestyle{{fancy}}
\\fancyhf{{}}
\\renewcommand{{\\headrulewidth}}{{0.4pt}}
\\fancyhead[L]{{\\small Prajñāpāramitāhṛdaya -- Parallel Edition}}
\\fancyhead[R]{{\\small 般若波羅蜜多心經}}
\\fancyfoot[C]{{\\thepage}}

{_FONTS_MAIN}

{_FONT_DEVANAGARI}

{_FONT_TIBETAN}

\\newcommand{{\\segnum}}[1]{{\\textbf{{[#1]}}}}
\\newcommand{{\\rom}}[1]{{{{\\scriptsize\\color{{gray}} #1}}}}
\\newcommand{{\\eng}}[1]{{\\multicolumn{{3}}{{@{{}}p{{0.96\\textwidth}}@{{}}}}{{\\small\\itshape #1}} \\\\[0.3em]}}
\\newcommand{{\\var}}[1]{{\\textsuperscript{{\\color{{red}}\\textbf{{#1}}}}}}
\\newcommand{{\\lemma}}[1]{{\\textbf{{#1}}}}
\\newcommand{{\\reading}}[1]{{#1}}
\\newcommand{{\\wit}}[1]{{\\textsc{{#1}}}}
\\newcommand{{\\depmark}}[2]{{{{\\scriptsize\\color{{blue}}[#1$\\to$#2]}}}}

\\begin{{document}}
"""


def _preamble_combined(provenance: str) -> str:
    return f"""{provenance}
\\documentclass[10pt,landscape,a4paper]{{article}}

\\usepackage[landscape,margin=1.2cm,bottom=2cm]{{geometry}}
\\usepackage{{fontspec}}
\\usepackage{{xeCJK}}
\\usepackage{{tabularx}}
\\usepackage{{array}}
\\usepackage{{booktabs}}
\\usepackage{{xcolor}}
\\usepackage{{longtable}}
\\usepackage{{multicol}}
\\usepackage[perpage]{{footmisc}}
\\usepackage{{fancyhdr}}
\\pagestyle{{fancy}}
\\fancyhf{{}}
\\renewcommand{{\\headrulewidth}}{{0.4pt}}
\\fancyhead[L]{{\\small Prajñāpāramitāhṛdaya -- Combined Critical Edition}}
\\fancyhead[R]{{\\small 般若波羅蜜多心經}}
\\fancyfoot[C]{{\\thepage}}
\\usepackage{{hyperref}}
\\hypersetup{{colorlinks=true,linkcolor=blue}}

{_FONTS_MAIN}

{_FONT_DEVANAGARI}

{_FONT_TIBETAN}

\\newcommand{{\\segnum}}[1]{{\\textbf{{[#1]}}}}
\\newcommand{{\\rom}}[1]{{{{\\small\\color{{gray}} #1}}}}
\\newcommand{{\\engltrans}}[1]{{\\multicolumn{{3}}{{p{{0.95\\textwidth}}}}{{\\small\\itshape #1}} \\\\}}
\\newcommand{{\\var}}[1]{{{{\\color{{red}}\\textsuperscript{{\\textbf{{#1}}}}}}}}
\\newcommand{{\\lemma}}[1]{{\\textbf{{#1}}}}
\\newcommand{{\\reading}}[1]{{#1}}
\\newcommand{{\\wit}}[1]{{\\textsc{{#1}}}}
\\newcommand{{\\depmark}}[2]{{{{\\scriptsize\\color{{blue}}[#1$\\to$#2]}}}}

\\begin{{document}}
"""


# ============================================================================
# Generators
# ============================================================================

class ChineseCriticalGen:
    """Generate the Chinese critical edition LaTeX."""

    def __init__(self, loader: DataLoader, assembler: ApparatusAssembler):
        self.loader = loader
        self.assembler = assembler

    def generate(self, data_hash: str) -> str:
        """Return complete LaTeX for chinese_critical.tex."""
        parts = [_preamble_chinese(_provenance_header(data_hash))]
        parts.append(self._title_page())
        parts.append("\\newpage\n\n\\section*{Text}\n")

        line_num = 1
        for i, (section_key, section_title) in enumerate(SECTIONS):
            parts.append(f"\n\\subsection*{{Section {_roman(i + 1)}: {section_title}}}\n")
            section_tex, line_num = self._generate_section(section_key, line_num)
            parts.append(section_tex)

        parts.append("\n\\end{document}\n")
        return "".join(parts)

    def _title_page(self) -> str:
        lines = [
            r"\begin{center}",
            r"{\Huge\bfseries 般若波羅蜜多心經}\\[0.5em]",
            r"{\LARGE Prajñāpāramitāhṛdaya}\\[0.3em]",
            r"{\Large Heart Sūtra}\\[1.5em]",
            r"{\large Chinese Critical Edition}\\[0.5em]",
            r"{\normalsize Based on T251 (Xuanzang, ca.\ 649--656 CE)}\\[2em]",
            r"\end{center}",
            "",
            r"\hrule",
            r"\vspace{1em}",
            "",
            r"\section*{Witnesses}",
            "",
            r"\begin{description}[leftmargin=2cm, labelwidth=1.8cm]",
        ]
        # Add witness descriptions from loaded data
        for wid in ["T251", "T250", "Fangshan", "T256", "T257"]:
            w = self.loader.load_witness(wid)
            title = w.get("title_chinese", wid)
            date = w.get("date", "")
            lines.append(
                f"\\item[\\wit{{{wid}}}] {title}"
                + (f" ({date})" if date else "")
                + "."
            )
        lines.append(r"\end{description}")
        lines.append(r"\vspace{1em}")
        return "\n".join(lines) + "\n"

    def _generate_section(self, section_key: str, line_num: int) -> tuple[str, int]:
        """Generate LaTeX for one section. Returns (tex, next_line_num)."""
        vt = self.loader.load_variant_table()
        entries = vt.get("sections", {}).get(section_key, [])
        if not entries:
            return "", line_num

        entry = entries[0]  # One entry per section
        base_text = entry["base_text"]
        segment_id = entry["segment_id"]

        # Get enrichment from T251
        t251_seg = self.loader.get_segment("T251", segment_id)
        pinyin = t251_seg.get("pinyin", "")
        gloss = t251_seg.get("english_gloss", "")

        # Build apparatus entries
        apparatus = self.assembler.assemble_chinese(section_key)

        # Split text into clauses
        clauses = _split_chinese_clauses(base_text)

        parts = []
        for clause in clauses:
            # Check if any apparatus entry's lemma appears in this clause
            footnotes = ""
            for app in apparatus:
                if app.lemma and app.lemma in clause:
                    footnotes += self._format_footnote(app)

            parts.append(
                f"\\linenum{{{line_num}}} {clause}{footnotes}\\\\\n"
                f"\\pinyin{{{_escape_latex(self._get_pinyin_for_clause(pinyin, clause, clauses))}}}\\\\[0.3em]"
            )
            line_num += 1

        parts.append("")
        parts.append(f"\\vspace{{0.5em}}")
        if gloss:
            parts.append(f"\\gloss{{{_escape_latex(gloss)}}}")
            parts.append("")
            parts.append(f"\\vspace{{0.3em}}")
            parts.append(f"\\fluent{{{_escape_latex(gloss)}}}")
        parts.append(f"\n\\vspace{{1em}}")

        return "\n".join(parts) + "\n", line_num

    def _get_pinyin_for_clause(
        self, full_pinyin: str, clause: str, all_clauses: list[str]
    ) -> str:
        """Extract the pinyin portion corresponding to a clause.

        Splits the full pinyin proportionally by clause position.
        """
        if not full_pinyin:
            return ""
        # Split pinyin at commas/periods to match clause structure
        pinyin_parts = re.split(r"[,，.。;；]\s*", full_pinyin)
        pinyin_parts = [p.strip() for p in pinyin_parts if p.strip()]
        idx = 0
        for i, c in enumerate(all_clauses):
            if c == clause:
                idx = i
                break
        if idx < len(pinyin_parts):
            return pinyin_parts[idx]
        return full_pinyin

    def _format_footnote(self, app: ApparatusEntry) -> str:
        """Format an apparatus entry as a LaTeX footnote."""
        parts = [f"\\footnote{{\\lemma{{{app.lemma}}}] "]
        for reading, witnesses in app.readings:
            wit_str = ", ".join(f"\\wit{{{w}}}" for w in witnesses)
            # Show a short excerpt of the variant reading
            short_reading = reading[:30] + ("…" if len(reading) > 30 else "")
            parts.append(f"\\reading{{{short_reading}}} {wit_str}. ")
        if app.note:
            parts.append(_escape_latex(app.note))
        parts.append("}")
        return "".join(parts)


class SanskritCriticalGen:
    """Generate the Sanskrit critical edition LaTeX."""

    def __init__(self, loader: DataLoader, assembler: ApparatusAssembler):
        self.loader = loader
        self.assembler = assembler

    def generate(self, data_hash: str) -> str:
        parts = [_preamble_sanskrit(_provenance_header(data_hash))]
        parts.append(self._title_page())
        parts.append("\\newpage\n\n\\section*{Text}\n")

        line_num = 1
        for i, (section_key, section_title) in enumerate(SECTIONS):
            parts.append(f"\n\\subsection*{{Section {_roman(i + 1)}: {section_title}}}\n")
            section_tex, line_num = self._generate_section(section_key, line_num)
            parts.append(section_tex)

        parts.append("\n\\end{document}\n")
        return "".join(parts)

    def _title_page(self) -> str:
        lines = [
            r"\begin{center}",
            r"{\Huge\bfseries\deva{प्रज्ञापारमिताहृदय}}\\[0.5em]",
            r"{\LARGE Prajñāpāramitāhṛdaya}\\[0.3em]",
            r"{\Large Heart Sūtra}\\[1.5em]",
            r"{\large Sanskrit Critical Edition}\\[0.5em]",
            r"{\normalsize Based on GRETIL text (following Conze 1967)}\\[2em]",
            r"\end{center}",
            "",
            r"\hrule",
            r"\vspace{1em}",
            "",
            r"\section*{Editorial Note}",
            "",
            r"Following \textcite{nattier1992}, this edition treats the Sanskrit",
            r"text as a back-translation from Chinese. The base text is the GRETIL",
            r"digital edition, which follows Conze's critical text.",
            "",
            r"\vspace{1em}",
        ]
        return "\n".join(lines) + "\n"

    def _generate_section(self, section_key: str, line_num: int) -> tuple[str, int]:
        vt = self.loader.load_variant_table()
        entries = vt.get("sections", {}).get(section_key, [])
        if not entries:
            return "", line_num

        entry = entries[0]
        segment_id = entry["segment_id"]

        # Get Sanskrit data
        gretil_seg = self.loader.get_segment_by_parallel("GRETIL", segment_id)
        if not gretil_seg:
            return "", line_num

        iast = gretil_seg.get("iast", "")
        devanagari = gretil_seg.get("devanagari", "")
        gloss = gretil_seg.get("english_gloss", "")
        note = gretil_seg.get("note", "")

        # Build cross-linguistic apparatus
        apparatus = self.assembler.assemble_cross_linguistic(section_key, "sanskrit")

        parts = []
        # Devanagari text
        if devanagari:
            parts.append(f"\\deva{{{devanagari}}}")
            parts.append("")

        # IAST text with line numbers
        footnote = ""
        if note:
            footnote = f"\\footnote{{{_escape_latex(note)}}}"
        parts.append(f"\\linenum{{{line_num}}} {iast}{footnote}\\\\[0.3em]")
        line_num += 1

        if gloss:
            parts.append(f"\n\\vspace{{0.5em}}")
            parts.append(f"\\gloss{{{_escape_latex(gloss)}}}")
            parts.append(f"\n\\vspace{{0.3em}}")
            parts.append(f"\\fluent{{{_escape_latex(gloss)}}}")

        parts.append(f"\n\\vspace{{1em}}")
        return "\n".join(parts) + "\n", line_num


class TibetanCriticalGen:
    """Generate the Tibetan critical edition LaTeX."""

    def __init__(self, loader: DataLoader, assembler: ApparatusAssembler):
        self.loader = loader
        self.assembler = assembler

    def generate(self, data_hash: str) -> str:
        parts = [_preamble_tibetan(_provenance_header(data_hash))]
        parts.append(self._title_page())
        parts.append("\\newpage\n\n\\section*{Text}\n")

        line_num = 1
        for i, (section_key, section_title) in enumerate(SECTIONS):
            parts.append(f"\n\\subsection*{{Section {_roman(i + 1)}: {section_title}}}\n")
            section_tex, line_num = self._generate_section(section_key, line_num)
            parts.append(section_tex)

        parts.append("\n\\end{document}\n")
        return "".join(parts)

    def _title_page(self) -> str:
        lines = [
            r"\begin{center}",
            r"{\Huge\bfseries\tib{བཅོམ་ལྡན་འདས་མ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོ}}\\[0.5em]",
            r"{\LARGE Prajñāpāramitāhṛdaya}\\[0.3em]",
            r"{\Large Heart Sūtra}\\[1.5em]",
            r"{\large Tibetan Critical Edition}\\[0.5em]",
            r"{\normalsize Based on Degé Kangyur (Toh 21)}\\[2em]",
            r"\end{center}",
            "",
            r"\hrule",
            r"\vspace{1em}",
            "",
            r"\section*{Transmission}",
            "",
            r"The Tibetan translation was made from Sanskrit by Vimalamitra",
            r"and Rinchen Dé, revised by Gewé Lodrö and Namkha.",
            r"The Degé edition represents the long recension with frame narrative.",
            "",
            r"\vspace{1em}",
        ]
        return "\n".join(lines) + "\n"

    def _generate_section(self, section_key: str, line_num: int) -> tuple[str, int]:
        vt = self.loader.load_variant_table()
        entries = vt.get("sections", {}).get(section_key, [])
        if not entries:
            return "", line_num

        entry = entries[0]
        segment_id = entry["segment_id"]

        # Get Tibetan data
        tib_seg = self.loader.get_segment_by_parallel("Toh21", segment_id)
        if not tib_seg:
            return "", line_num

        tibetan = tib_seg.get("tibetan", "")
        wylie = tib_seg.get("wylie", "")
        gloss = tib_seg.get("english_gloss", "")
        note = tib_seg.get("note", "")

        parts = []
        footnote = ""
        if note:
            footnote = f"\\footnote{{{_escape_latex(note)}}}"

        parts.append(f"\\linenum{{{line_num}}} \\tib{{{tibetan}}}{footnote}\\\\")
        parts.append(f"\\wylie{{{wylie}}}\\\\[0.3em]")
        line_num += 1

        if gloss:
            parts.append(f"\n\\vspace{{0.5em}}")
            parts.append(f"\\gloss{{{_escape_latex(gloss)}}}")
            parts.append(f"\n\\vspace{{0.3em}}")
            parts.append(f"\\fluent{{{_escape_latex(gloss)}}}")

        parts.append(f"\n\\vspace{{1em}}")
        return "\n".join(parts) + "\n", line_num


class ParallelGen:
    """Generate the parallel synoptic edition LaTeX (landscape longtable)."""

    def __init__(self, loader: DataLoader):
        self.loader = loader

    def generate(self, data_hash: str) -> str:
        parts = [_preamble_parallel(_provenance_header(data_hash))]
        parts.append(self._title_page())
        parts.append(self._table_header())

        for i, (section_key, section_title) in enumerate(SECTIONS):
            parts.append(self._generate_segment(section_key, i + 1))

        parts.append(r"\end{longtable}")
        parts.append("\n\\end{document}\n")
        return "".join(parts)

    def _title_page(self) -> str:
        lines = [
            r"\begin{center}",
            r"{\Huge\bfseries Prajñāpāramitāhṛdaya}\\[0.3em]",
            r"{\Huge 般若波羅蜜多心經}\\[0.5em]",
            r"{\Large Heart Sūtra}\\[1em]",
            r"{\Large Parallel Synoptic Edition}\\[0.5em]",
            r"{\normalsize Chinese · Sanskrit · Tibetan}\\[2em]",
            r"\end{center}",
            "",
            r"\hrule",
            r"\vspace{1em}",
            "",
        ]
        return "\n".join(lines) + "\n"

    def _table_header(self) -> str:
        return r"""
\footnotesize

\begin{longtable}{|>{\raggedright\arraybackslash}p{0.28\textwidth}|>{\raggedright\arraybackslash}p{0.34\textwidth}|>{\raggedright\arraybackslash}p{0.32\textwidth}|}
\hline
\textbf{Chinese (T251)} & \textbf{Sanskrit} & \textbf{Tibetan (Toh 21)} \\
\hline
\hline
\endfirsthead

\hline
\textbf{Chinese (T251)} & \textbf{Sanskrit} & \textbf{Tibetan (Toh 21)} \\
\hline
\hline
\endhead

\hline
\multicolumn{3}{r}{\small\itshape continued...}
\endfoot

\hline
\endlastfoot

"""

    def _generate_segment(self, section_key: str, seg_num: int) -> str:
        vt = self.loader.load_variant_table()
        entries = vt.get("sections", {}).get(section_key, [])
        if not entries:
            return ""

        entry = entries[0]
        segment_id = entry["segment_id"]
        base_text = entry["base_text"]

        # Get enrichment
        t251_seg = self.loader.get_segment("T251", segment_id)
        pinyin = t251_seg.get("pinyin", "")
        gloss = t251_seg.get("english_gloss", "")

        gretil_seg = self.loader.get_segment_by_parallel("GRETIL", segment_id)
        iast = gretil_seg.get("iast", "")
        devanagari = gretil_seg.get("devanagari", "")

        tib_seg = self.loader.get_segment_by_parallel("Toh21", segment_id)
        tibetan = tib_seg.get("tibetan", "")
        wylie = tib_seg.get("wylie", "")

        # Build row
        zh_col = f"\\segnum{{{seg_num}}} {base_text}\n\\newline\\rom{{{_escape_latex(pinyin)}}}"
        sa_col = ""
        if devanagari:
            sa_col += f"\\deva{{{devanagari}}}\n\\newline"
        sa_col += f"\\rom{{{iast}}}"
        bo_col = ""
        if tibetan:
            bo_col += f"\\tib{{{tibetan}}}\n\\newline"
        bo_col += f"\\rom{{{wylie}}}"

        parts = [
            f"{zh_col}\n&\n{sa_col}\n&\n{bo_col}\n\\\\",
            r"\hline",
        ]
        if gloss:
            parts.append(f"\\eng{{{_escape_latex(gloss)}}}")
            parts.append(r"\hline")
            parts.append(r"\hline")

        return "\n".join(parts) + "\n\n"


class CombinedCriticalGen:
    """Generate the combined critical edition LaTeX (landscape longtable)."""

    def __init__(self, loader: DataLoader, assembler: ApparatusAssembler):
        self.loader = loader
        self.assembler = assembler
        self._var_counter = 0

    def generate(self, data_hash: str) -> str:
        self._var_counter = 0
        parts = [_preamble_combined(_provenance_header(data_hash))]
        parts.append(self._title_page())
        parts.append(self._table_header())

        all_apparatus: list[tuple[int, str]] = []
        for i, (section_key, section_title) in enumerate(SECTIONS):
            seg_tex, seg_apparatus = self._generate_segment(section_key, i + 1)
            parts.append(seg_tex)
            all_apparatus.extend(seg_apparatus)

        parts.append(r"\end{longtable}")
        parts.append("")

        # Apparatus section
        if all_apparatus:
            parts.append(r"\section*{Critical Apparatus}")
            parts.append(r"\footnotesize")
            parts.append(r"\begin{multicols}{2}")
            for num, note in all_apparatus:
                parts.append(f"\\var{{{num}}}~{note}\n")
            parts.append(r"\end{multicols}")

        parts.append("\n\\end{document}\n")
        return "".join(parts)

    def _title_page(self) -> str:
        lines = [
            r"\begin{center}",
            r"{\Huge\bfseries Prajñāpāramitāhṛdaya}\\[0.3em]",
            r"{\Huge 般若波羅蜜多心經}\\[0.3em]",
            r"{\huge\deva{प्रज्ञापारमिताहृदय}}\\[0.5em]",
            r"{\LARGE Heart Sūtra}\\[1em]",
            r"{\Large Combined Critical Edition}\\[0.5em]",
            r"{\normalsize Chinese · Sanskrit · Tibetan}\\[2em]",
            r"\end{center}",
            "",
            r"\hrule",
            r"\vspace{1em}",
            "",
        ]
        return "\n".join(lines) + "\n"

    def _table_header(self) -> str:
        return r"""
\footnotesize

\begin{longtable}{|>{\raggedright\arraybackslash}p{0.30\textwidth}|>{\raggedright\arraybackslash}p{0.36\textwidth}|>{\raggedright\arraybackslash}p{0.28\textwidth}|}
\hline
\textbf{Chinese (T251)} & \textbf{Sanskrit} & \textbf{Tibetan (Toh 21)} \\
\hline
\hline
\endfirsthead

\hline
\textbf{Chinese (T251)} & \textbf{Sanskrit} & \textbf{Tibetan (Toh 21)} \\
\hline
\hline
\endhead

\hline
\multicolumn{3}{r}{\small\itshape continued...}
\endfoot

\hline
\endlastfoot

"""

    def _generate_segment(
        self, section_key: str, seg_num: int
    ) -> tuple[str, list[tuple[int, str]]]:
        vt = self.loader.load_variant_table()
        entries = vt.get("sections", {}).get(section_key, [])
        if not entries:
            return "", []

        entry = entries[0]
        segment_id = entry["segment_id"]
        base_text = entry["base_text"]

        # Get enrichment
        t251_seg = self.loader.get_segment("T251", segment_id)
        pinyin = t251_seg.get("pinyin", "")
        gloss = t251_seg.get("english_gloss", "")

        gretil_seg = self.loader.get_segment_by_parallel("GRETIL", segment_id)
        iast = gretil_seg.get("iast", "")
        devanagari = gretil_seg.get("devanagari", "")

        tib_seg = self.loader.get_segment_by_parallel("Toh21", segment_id)
        tibetan = tib_seg.get("tibetan", "")
        wylie = tib_seg.get("wylie", "")

        # Collect apparatus entries
        apparatus_notes = []
        for variant in entry.get("variants", []):
            if variant.get("note"):
                self._var_counter += 1
                note_text = _escape_latex(variant["note"])
                witnesses = ", ".join(
                    f"\\wit{{{w}}}" for w in variant.get("witnesses", [])
                )
                apparatus_notes.append(
                    (self._var_counter, f"{witnesses}: {note_text}")
                )

        # Build columns
        zh_col = f"\\segnum{{{seg_num}}} {base_text}\n\\newline\\rom{{{_escape_latex(pinyin)}}}"
        sa_col = ""
        if devanagari:
            sa_col += f"\\deva{{{devanagari}}}\n\\newline"
        sa_col += f"\\rom{{{iast}}}"
        bo_col = ""
        if tibetan:
            bo_col += f"\\tib{{{tibetan}}}\n\\newline"
        bo_col += f"\\rom{{{wylie}}}"

        parts = [
            f"{zh_col}\n&\n{sa_col}\n&\n{bo_col}\n\\\\",
            r"\hline",
        ]
        if gloss:
            parts.append(f"\\engltrans{{{_escape_latex(gloss)}}}")
            parts.append(r"\hline")
            parts.append(r"\hline")

        return "\n".join(parts) + "\n\n", apparatus_notes


# ============================================================================
# Figure Snippets (for DSH paper)
# ============================================================================

class FigureSnippetGen:
    """Generate figure excerpt snippets for the DSH paper.

    Each snippet is a LaTeX fragment (no preamble) suitable for \\input
    inside a \\begin{figure} environment. The data comes from the same
    DataLoader and ApparatusAssembler used by the full editions, so the
    figures stay in sync with the generated output.
    """

    # Marker format: bold superscript for visibility against CJK/Tibetan
    MARKER_FMT = "\\textsuperscript{{\\textbf{{{letter}}}}}"

    def __init__(self, loader: DataLoader, assembler: ApparatusAssembler):
        self.loader = loader
        self.assembler = assembler

    @classmethod
    def _marker(cls, letter: str) -> str:
        """Return a bold superscript marker for a given letter."""
        return cls.MARKER_FMT.format(letter=letter)

    def generate_all(self) -> dict[str, str]:
        """Return {filename: content} for all figure snippets."""
        return {
            "figure_chinese_mantra.tex": self._chinese_mantra(),
            "figure_sanskrit_mantra.tex": self._sanskrit_mantra(),
            "figure_tibetan_pratityasamutpada.tex": self._tibetan_pratityasamutpada(),
        }

    def _chinese_mantra(self) -> str:
        """Generate Chinese mantra figure snippet (Figure 2 in DSH paper)."""
        vt = self.loader.load_variant_table()
        entry = vt["sections"]["mantra"][0]
        base_text = entry["base_text"]

        apparatus = self.assembler.assemble_chinese("mantra")

        # Group apparatus entries that share the same lemma position
        # into a single marker with multiple readings
        groups: dict[int, list[ApparatusEntry]] = {}
        for app in apparatus:
            pos = base_text.find(app.lemma)
            if pos < 0:
                pos = 0
            groups.setdefault(pos, []).append(app)

        # Build markers: one letter per unique position
        sorted_positions = sorted(groups.keys())
        pos_to_letter = {}
        for i, pos in enumerate(sorted_positions):
            pos_to_letter[pos] = chr(ord("a") + i)

        # For CJK text, place the marker at the end of the passage
        # (before the final period) rather than mid-word, since a tiny
        # Latin superscript is invisible between CJK characters.
        # Use \hspace{0pt} to prevent the superscript from being
        # swallowed by CJK character spacing.
        marked_text = base_text
        for pos in reversed(sorted_positions):
            letter = pos_to_letter[pos]
            # Place at end of text (before final 。) where it's visible
            insert_at = len(marked_text)
            idx = marked_text.rfind("。")
            if idx > 0:
                insert_at = idx
            marked_text = (
                marked_text[:insert_at]
                + "\\hspace{0pt}" + self._marker(letter)
                + marked_text[insert_at:]
            )

        # Build apparatus section: one entry per marker, listing all witnesses
        app_lines = []
        for pos in sorted_positions:
            letter = pos_to_letter[pos]
            entries = groups[pos]
            lemma = entries[0].lemma
            # Collect all readings from all entries at this position
            reading_parts = []
            combined_note_parts = []
            for app in entries:
                for reading, witnesses in app.readings:
                    wit_str = ", ".join(f"\\wit{{{w}}}" for w in witnesses)
                    short = reading[:50] + ("\\ldots " if len(reading) > 50 else "")
                    reading_parts.append(f"{short} {wit_str}")
                if app.note:
                    combined_note_parts.append(_escape_latex(app.note))
            readings_str = "; ".join(reading_parts)
            note = ""
            if combined_note_parts:
                note = " " + " ".join(combined_note_parts)
            app_lines.append(
                f"{self._marker(letter)}~{lemma}] "
                f"{readings_str}.{note}"
            )

        parts = [
            "\\fbox{\\parbox{0.92\\textwidth}{\\small",
            f"\\textbf{{Section {_roman(12)}: {SECTION_TITLES['mantra']}}} "
            "(Chinese critical edition excerpt)\\\\[0.5em]",
            f"{marked_text}\\\\[0.4em]",
            "\\rule{\\linewidth}{0.3pt}\\\\[0.3em]",
        ]
        parts.extend(
            line + ("\\\\[0.2em]" if i < len(app_lines) - 1 else "")
            for i, line in enumerate(app_lines)
        )
        parts.append("}}")

        return "\n".join(parts) + "\n"

    def _sanskrit_mantra(self) -> str:
        """Generate Sanskrit mantra figure snippet (Figure 3 in DSH paper)."""
        vt = self.loader.load_variant_table()
        entry = vt["sections"]["mantra"][0]
        segment_id = entry["segment_id"]

        gretil_seg = self.loader.get_segment_by_parallel("GRETIL", segment_id)
        iast = gretil_seg.get("iast", "")
        devanagari = gretil_seg.get("devanagari", "")
        note = gretil_seg.get("note", "")

        # Also check variant table for the cross-linguistic note
        for variant in entry.get("variants", []):
            if "GRETIL" in variant.get("witnesses", []) and variant.get("note"):
                note = variant["note"]
                break

        # Split Devanagari around ॐ for superscript marker
        deva_parts = devanagari.split("ॐ", 1)
        if len(deva_parts) == 2:
            deva_line = (
                f"\\deva{{{deva_parts[0]}}}"
                f"\\deva{{ॐ}}{self._marker('a')} "
                f"\\deva{{{deva_parts[1].lstrip()}}}"
            )
        else:
            deva_line = f"\\deva{{{devanagari}}}"

        # Split IAST around Oṃ for superscript marker
        iast_parts = iast.split("Oṃ", 1)
        if len(iast_parts) == 2:
            iast_line = (
                f"{iast_parts[0]}"
                f"Oṃ{self._marker('a')}"
                f"{iast_parts[1]}"
            )
        else:
            iast_line = iast

        # Apparatus
        app_note = _escape_latex(note) if note else ""

        parts = [
            "\\fbox{\\parbox{0.92\\textwidth}{\\small",
            f"\\textbf{{Section {_roman(12)}: {SECTION_TITLES['mantra']}}} "
            "(Sanskrit critical edition excerpt)\\\\[0.5em]",
            f"{deva_line}\\\\[0.4em]",
            f"{iast_line}\\\\[0.4em]",
            "\\rule{\\linewidth}{0.3pt}\\\\[0.3em]",
            f"{self._marker('a')}~\\deva{{ॐ}} Oṃ] {app_note}",
            "}}",
        ]

        return "\n".join(parts) + "\n"

    def _tibetan_pratityasamutpada(self) -> str:
        """Generate Tibetan pratītyasamutpāda figure snippet (Figure 4)."""
        vt = self.loader.load_variant_table()
        entry = vt["sections"]["negations_pratityasamutpada"][0]
        segment_id = entry["segment_id"]

        tib_seg = self.loader.get_segment_by_parallel("Toh21", segment_id)
        tibetan = tib_seg.get("tibetan", "")
        wylie = tib_seg.get("wylie", "")
        note = tib_seg.get("note", "")

        # Also check variant table for the cross-linguistic note
        for variant in entry.get("variants", []):
            if "Toh21" in variant.get("witnesses", []) and variant.get("note"):
                note = variant["note"]
                break

        # Place marker after the full Tibetan line where it's visible,
        # rather than splitting \tib{} mid-word (which causes rendering
        # issues with the tsek and font switching).
        tib_line = f"\\tib{{{tibetan}}}{self._marker('a')}"

        # Wylie transliteration
        wylie_line = f"\\textit{{{wylie}}}"

        # Apparatus
        app_note = _escape_latex(note) if note else ""

        parts = [
            "\\fbox{\\parbox{0.92\\textwidth}{\\small",
            f"\\textbf{{Section {_roman(7)}: "
            f"{SECTION_TITLES['negations_pratityasamutpada']}}} "
            "(Tibetan critical edition excerpt)\\\\[0.5em]",
            f"{tib_line}\\\\[0.2em]",
            f"{wylie_line}\\\\[0.4em]",
            "\\rule{\\linewidth}{0.3pt}\\\\[0.3em]",
            f"{self._marker('a')}~\\tib{{ཟད་པ}} "
            "(\\textit{zad pa}, `exhaustion')] "
            f"{app_note}",
            "}}",
        ]

        return "\n".join(parts) + "\n"


# ============================================================================
# Orchestrator
# ============================================================================

class LatexEditionBuilder:
    """Orchestrate generation of all LaTeX editions."""

    def __init__(self, data_dir: Path, output_dir: Path):
        self.data_dir = data_dir
        self.output_dir = output_dir
        self.loader = DataLoader(data_dir)
        self.assembler = ApparatusAssembler(self.loader)
        self.data_hash = compute_data_hash(data_dir)

    def generate_all(self) -> dict[str, Path]:
        """Generate all five editions plus figure snippets."""
        results = {}
        for name in ["chinese", "sanskrit", "tibetan", "parallel", "combined"]:
            path = self.generate_one(name)
            results[name] = path
        # Also generate figure snippets
        fig_results = self.generate_figures()
        results.update(fig_results)
        return results

    def generate_figures(self) -> dict[str, Path]:
        """Generate figure snippet files for the DSH paper."""
        gen = FigureSnippetGen(self.loader, self.assembler)
        snippets = gen.generate_all()
        fig_dir = self.output_dir / "figures"
        fig_dir.mkdir(parents=True, exist_ok=True)
        results = {}
        for filename, content in snippets.items():
            out_path = fig_dir / filename
            out_path.write_text(content, encoding="utf-8")
            logger.info("Generated figure %s (%d bytes)", out_path, len(content))
            results[f"figure:{filename}"] = out_path
        return results

    def generate_one(self, edition: str) -> Path:
        """Generate a single edition. Returns the output path."""
        generators = {
            "chinese": (
                ChineseCriticalGen(self.loader, self.assembler),
                "chinese_critical.tex",
            ),
            "sanskrit": (
                SanskritCriticalGen(self.loader, self.assembler),
                "sanskrit_critical.tex",
            ),
            "tibetan": (
                TibetanCriticalGen(self.loader, self.assembler),
                "tibetan_critical.tex",
            ),
            "parallel": (
                ParallelGen(self.loader),
                "parallel_complete.tex",
            ),
            "combined": (
                CombinedCriticalGen(self.loader, self.assembler),
                "heart_sutra_critical.tex",
            ),
        }
        if edition not in generators:
            raise ValueError(f"Unknown edition: {edition}")

        gen, filename = generators[edition]
        content = gen.generate(self.data_hash)
        out_path = self.output_dir / filename
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        logger.info("Generated %s (%d bytes)", out_path, len(content))
        return out_path


# ============================================================================
# Utilities
# ============================================================================

def _roman(n: int) -> str:
    """Convert integer to Roman numeral string."""
    vals = [
        (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),
        (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
        (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"),
    ]
    result = ""
    for value, numeral in vals:
        while n >= value:
            result += numeral
            n -= value
    return result


# ============================================================================
# CLI
# ============================================================================

def generate_editions(
    data_dir: Path | None = None,
    output_dir: Path | None = None,
    edition: str = "all",
) -> dict[str, Path]:
    """Top-level function for generating LaTeX editions.

    Args:
        data_dir: Path to data directory (auto-resolved if None).
        output_dir: Path to output directory (default: output/latex/).
        edition: Which edition to generate ("all" or specific name).

    Returns:
        Dict mapping edition names to output paths.
    """
    resolved_data = resolve_data_dir(data_dir)
    if output_dir is None:
        output_dir = resolved_data.parent / "output" / "latex"

    builder = LatexEditionBuilder(resolved_data, output_dir)

    if edition == "all":
        return builder.generate_all()
    elif edition == "figures":
        return builder.generate_figures()
    else:
        path = builder.generate_one(edition)
        return {edition: path}


def main() -> None:
    """CLI entry point."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate LaTeX critical editions from collation data."
    )
    parser.add_argument(
        "--edition",
        choices=["chinese", "sanskrit", "tibetan", "parallel", "combined", "figures", "all"],
        default="all",
        help="Which edition to generate (default: all).",
    )
    parser.add_argument("--data-dir", default=None, help="Path to data directory.")
    parser.add_argument("--output-dir", default=None, help="Path to output directory.")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    data_dir = Path(args.data_dir) if args.data_dir else None
    output_dir = Path(args.output_dir) if args.output_dir else None

    results = generate_editions(data_dir, output_dir, args.edition)
    for name, path in results.items():
        print(f"  {name}: {path}")


if __name__ == "__main__":
    main()
