"""TEI-XML export for the Heart Sutra critical edition.

Generates a TEI P5 XML document containing all three traditions
(Chinese, Sanskrit, Tibetan) with cross-linguistic alignment via
<standOff>/<linkGrp> and in-line critical apparatus.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from datetime import datetime, timezone

from lxml import etree

from hrdaya.data import resolve_data_dir, DATA_VERSION, compute_data_hash

logger = logging.getLogger(__name__)

TEI_NS = "http://www.tei-c.org/ns/1.0"
XML_NS = "http://www.w3.org/XML/1998/namespace"
NSMAP = {None: TEI_NS}


def _element(tag: str, text: str | None = None, **attribs) -> etree._Element:
    """Create a TEI-namespaced element."""
    el = etree.Element(f"{{{TEI_NS}}}{tag}", nsmap=NSMAP)
    if text is not None:
        el.text = text
    for k, v in attribs.items():
        if k == "xml_id":
            el.set(f"{{{XML_NS}}}id", v)
        elif k == "xml_lang":
            el.set(f"{{{XML_NS}}}lang", v)
        else:
            el.set(k, v)
    return el


def _sub(parent: etree._Element, tag: str, text: str | None = None,
         **attribs) -> etree._Element:
    """Create a TEI-namespaced subelement."""
    el = _element(tag, text, **attribs)
    parent.append(el)
    return el


def _load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _seg_xml_id(seg_id: str) -> str:
    """Generate a valid XML NCName ID for a segment.

    Segment IDs like 'T251:1' or 'IOL Tib J 751:3' are already unique,
    so we sanitize for XML NCName compliance:
    - Replace spaces and colons with underscores/hyphens
    - Prefix with 'w' if the ID starts with a digit
    """
    if not seg_id:
        return "w_unknown"
    result = seg_id.replace(" ", "_").replace(":", "-")
    if result[0].isdigit() or result[0] in "-.":
        result = "w" + result
    return result


def _load_tradition_witnesses(data_dir: Path,
                               tradition: str) -> list[dict]:
    """Load all witness JSON files for a tradition."""
    witnesses = []
    tradition_dir = data_dir / tradition
    if not tradition_dir.exists():
        return witnesses
    for json_path in sorted(tradition_dir.rglob("*.json")):
        try:
            data = _load_json(json_path)
            if "segments" in data:
                witnesses.append(data)
            else:
                logger.debug("Skipping %s: no 'segments' key", json_path.name)
        except json.JSONDecodeError as e:
            logger.warning("Malformed JSON in %s: %s", json_path.name, e)
            continue
    return witnesses


def generate_tei_header(data_dir: Path,
                        all_witnesses: list[dict] | None = None,
                        ) -> etree._Element:
    """Generate <teiHeader> with file description and encoding info.

    Parameters
    ----------
    data_dir : Path
        Path to the data directory (used for hash/version info).
    all_witnesses : list[dict], optional
        Pre-loaded witness dicts. If None, witnesses are loaded from disk.
    """
    header = _element("teiHeader")

    # fileDesc
    file_desc = _sub(header, "fileDesc")

    title_stmt = _sub(file_desc, "titleStmt")
    _sub(title_stmt, "title",
         "Prajñāpāramitāhṛdaya: A Computational Critical Edition")
    _sub(title_stmt, "author", "Dan Zigmond")

    pub_stmt = _sub(file_desc, "publicationStmt")
    _sub(pub_stmt, "p",
         "Generated by the hrdaya Python package. "
         f"Data version {DATA_VERSION}.")

    source_desc = _sub(file_desc, "sourceDesc")
    list_wit = _sub(source_desc, "listWit")

    # Use pre-loaded witnesses if provided, otherwise load from disk
    if all_witnesses is not None:
        witness_list = all_witnesses
    else:
        witness_list = []
        for tradition in ("chinese", "sanskrit", "tibetan"):
            witness_list.extend(_load_tradition_witnesses(data_dir, tradition))

    for wit_data in witness_list:
        wit_id = wit_data.get("id", "unknown")
        safe_id = _seg_xml_id(wit_id)
        wit_el = _sub(list_wit, "witness", xml_id=safe_id)
        # Build description
        parts = [wit_id]
        if "attributed_translator" in wit_data:
            parts.append(f"({wit_data['attributed_translator']})")
        elif "source" in wit_data:
            parts.append(f"({wit_data['source']})")
        if "date" in wit_data:
            parts.append(wit_data["date"])
        wit_el.text = " ".join(parts)

    # encodingDesc
    encoding_desc = _sub(header, "encodingDesc")
    _sub(encoding_desc, "variantEncoding",
         method="parallel-segmentation", location="internal")

    proj_desc = _sub(encoding_desc, "projectDesc")
    _sub(proj_desc, "p",
         "Cross-linguistic critical edition of the Heart Sūtra "
         "(Prajñāpāramitāhṛdaya) spanning Chinese, Sanskrit, and Tibetan "
         "traditions. T251 serves as the alignment anchor for pragmatic "
         "reasons; this does not presuppose a direction of textual "
         "dependence.")

    # revisionDesc
    revision_desc = _sub(header, "revisionDesc")
    change = _sub(revision_desc, "change",
                  when=datetime.now(timezone.utc).strftime("%Y-%m-%d"))
    change.text = (f"Generated from hrdaya data version {DATA_VERSION}, "
                   f"hash {compute_data_hash(data_dir)}")

    return header


def _get_base_witness(witnesses: list[dict],
                       default_id: str) -> dict | None:
    """Find the base/default witness from a list."""
    for w in witnesses:
        if w.get("id") == default_id:
            return w
    return witnesses[0] if witnesses else None


def _group_segments_by_section(witness: dict) -> dict[str, list[dict]]:
    """Group a witness's segments by section name."""
    by_section: dict[str, list[dict]] = {}
    for seg in witness.get("segments", []):
        section = seg.get("section", "unknown")
        by_section.setdefault(section, []).append(seg)
    return by_section


def generate_chinese_text(witnesses: list[dict]) -> etree._Element:
    """Generate <text xml:lang="lzh"> for the Chinese tradition."""
    text_el = _element("text", xml_lang="lzh")
    body = _sub(text_el, "body")

    base = _get_base_witness(witnesses, "T251")
    if not base:
        return text_el

    alternates = [w for w in witnesses if w.get("id") != base.get("id")]
    alt_by_parallel = {}
    for alt in alternates:
        for seg in alt.get("segments", []):
            parallel = seg.get("base_parallel")
            if parallel:
                alt_by_parallel.setdefault(parallel, []).append(
                    (alt.get("id", "unknown"), seg))

    sections = _group_segments_by_section(base)
    for section_name, segs in sections.items():
        div = _sub(body, "div", type="section", n=section_name)
        for i, seg in enumerate(segs):
            seg_id = seg.get("id", f"zh-{i}")
            xml_id = _seg_xml_id(seg_id)
            seg_el = _sub(div, "seg", xml_id=xml_id)

            base_text = seg.get("text", "")
            variants = alt_by_parallel.get(seg_id, [])

            # Pre-filter variants that actually differ from the base
            differing = [
                (alt_id, alt_seg) for alt_id, alt_seg in variants
                if alt_seg.get("text", "") and alt_seg.get("text", "") != base_text
            ]
            if differing:
                app = _sub(seg_el, "app")
                safe_base = _seg_xml_id(base.get("id", "T251"))
                _sub(app, "lem", base_text, wit=f"#{safe_base}")
                for alt_id, alt_seg in differing:
                    safe_alt = _seg_xml_id(alt_id)
                    _sub(app, "rdg", alt_seg.get("text", ""), wit=f"#{safe_alt}")
            else:
                seg_el.text = base_text

    return text_el


def generate_sanskrit_text(witnesses: list[dict]) -> etree._Element:
    """Generate <text xml:lang="sa"> for the Sanskrit tradition.

    Note: Currently renders only the GRETIL base witness text without
    critical apparatus. The Horyuji manuscript lacks base_parallel
    alignment data needed for automated apparatus construction.
    """
    text_el = _element("text", xml_lang="sa")
    body = _sub(text_el, "body")

    base = _get_base_witness(witnesses, "GRETIL")
    if not base:
        return text_el

    sections = _group_segments_by_section(base)
    for section_name, segs in sections.items():
        div = _sub(body, "div", type="section", n=section_name)
        for i, seg in enumerate(segs):
            seg_id = seg.get("id", f"sa-{i}")
            xml_id = _seg_xml_id(seg_id)
            iast_text = seg.get("iast", "")
            _sub(div, "seg", iast_text, xml_id=xml_id)

    return text_el


def generate_tibetan_text(witnesses: list[dict]) -> etree._Element:
    """Generate <text xml:lang="bo"> for the Tibetan tradition.

    Note: Currently renders only the Toh21 (Kangyur) base witness
    text without critical apparatus. Tibetan variant data is captured
    in the collation output rather than the TEI export.
    """
    text_el = _element("text", xml_lang="bo")
    body = _sub(text_el, "body")

    base = _get_base_witness(witnesses, "Toh21")
    if not base:
        return text_el

    sections = _group_segments_by_section(base)
    for section_name, segs in sections.items():
        div = _sub(body, "div", type="section", n=section_name)
        for i, seg in enumerate(segs):
            seg_id = seg.get("id", f"bo-{i}")
            xml_id = _seg_xml_id(seg_id)
            tib_text = seg.get("tibetan", "")
            _sub(div, "seg", tib_text, xml_id=xml_id)

    return text_el


def generate_standoff_alignment(chinese_witnesses: list[dict],
                                 sanskrit_witnesses: list[dict],
                                 tibetan_witnesses: list[dict]
                                 ) -> etree._Element:
    """Generate <standOff> with cross-linguistic alignment links."""
    standoff = _element("standOff")
    link_grp = _sub(standoff, "linkGrp", type="translation-alignment")

    # Build alignment from base_parallel references
    zh_base = _get_base_witness(chinese_witnesses, "T251")
    sa_base = _get_base_witness(sanskrit_witnesses, "GRETIL")
    bo_base = _get_base_witness(tibetan_witnesses, "Toh21")

    if not zh_base:
        return standoff

    # Index Sanskrit and Tibetan segments by their base_parallel
    sa_by_parallel = {}
    if sa_base:
        for i, seg in enumerate(sa_base.get("segments", [])):
            parallel = seg.get("base_parallel")
            if parallel:
                sa_by_parallel[parallel] = seg.get("id", f"sa-{i}")

    bo_by_parallel = {}
    if bo_base:
        for i, seg in enumerate(bo_base.get("segments", [])):
            parallel = seg.get("base_parallel")
            if parallel:
                bo_by_parallel[parallel] = seg.get("id", f"bo-{i}")

    # Create links for each Chinese segment that has parallels
    for i, zh_seg in enumerate(zh_base.get("segments", [])):
        zh_id = zh_seg.get("id", f"zh-{i}")
        zh_xml_id = _seg_xml_id(zh_id)
        targets = [f"#{zh_xml_id}"]

        if zh_id in sa_by_parallel:
            sa_id = sa_by_parallel[zh_id]
            targets.append(f"#{_seg_xml_id(sa_id)}")

        if zh_id in bo_by_parallel:
            bo_id = bo_by_parallel[zh_id]
            targets.append(f"#{_seg_xml_id(bo_id)}")

        if len(targets) > 1:  # Only create link if there are parallels
            _sub(link_grp, "link", target=" ".join(targets))

    return standoff


def export_tei(output_path: str | Path | None = None,
               data_dir: str | Path | None = None) -> Path:
    """Generate and write the TEI-XML edition.

    Parameters
    ----------
    output_path : path, optional
        Where to write the XML. Defaults to output/tei/ in the repo.
    data_dir : path, optional
        Path to the data directory. Auto-resolved if not provided.

    Returns
    -------
    Path
        The path to the written XML file.
    """
    data_path = resolve_data_dir(data_dir)

    # Load witnesses
    zh_witnesses = _load_tradition_witnesses(data_path, "chinese")
    sa_witnesses = _load_tradition_witnesses(data_path, "sanskrit")
    bo_witnesses = _load_tradition_witnesses(data_path, "tibetan")

    # Build TEI document
    tei = _element("TEI")

    # Header (pass pre-loaded witnesses to avoid double I/O)
    all_witnesses = zh_witnesses + sa_witnesses + bo_witnesses
    tei.append(generate_tei_header(data_path, all_witnesses=all_witnesses))

    # StandOff alignment
    tei.append(generate_standoff_alignment(
        zh_witnesses, sa_witnesses, bo_witnesses))

    # Group with three text elements
    group = _sub(tei, "group")
    group.append(generate_chinese_text(zh_witnesses))
    group.append(generate_sanskrit_text(sa_witnesses))
    group.append(generate_tibetan_text(bo_witnesses))

    # Serialize
    tree = etree.ElementTree(tei)

    if output_path is None:
        repo_root = data_path.parent
        output_path = repo_root / "output" / "tei" / "heart_sutra_edition.xml"
    else:
        output_path = Path(output_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    tree.write(
        str(output_path),
        xml_declaration=True,
        encoding="UTF-8",
        pretty_print=True,
    )

    return output_path


if __name__ == "__main__":
    path = export_tei()
    print(f"TEI-XML written to {path}")
